const deityData = {
	domain: [
		{
			name: 'a geography',
			example: 'mountains, swamps, seas, rivers, deserts, volcanoes',
		},
		{
			name: 'something in nature',
			example: 'sunlight, storm, mushrooms, animals birth',
		},
		{
			name: 'an art or craft',
			example: 'smithing, the loom, arcana, knowledge, beer/wine, jewelry',
		},
		{
			name: 'an endeavor',
			example: 'war, travel, the hunt, harvest, games, music',
		},
		{
			name: 'something around the home',
			example: 'garden, bread, hearth, cats, love, family',
		},
		{
			name: 'something grim',
			example: 'death, grave, night, underworld, cannibalism, nightmares',
		},
		{
			name: 'celestial bodies',
			example: 'stars, comets, galaxies, nebulae, planets, auroras',
		},
		{
			name: 'seasons and weather',
			example: 'spring, winter, thunder, rainbows, hurricanes, fog',
		},
		{
			name: 'emotions and passions',
			example: 'love, hate, joy, sorrow, courage, fear',
		},
		{
			name: 'craftsmanship and creation',
			example:
				'architecture, sculpture, painting, invention, poetry, literature',
		},
		{
			name: 'deception and treachery',
			example: 'betrayal, deceit, espionage, sabotage, lies, double-crossing',
		},
	],
	symbol: [
		{
			name: 'weapon',
			examples: 'sword, dagger, hammer, arrow, spear, trident',
		},
		{
			name: 'tool',
			examples: 'scythe, pick, wheel, cup, key, horseshoe',
		},
		{
			name: 'animal',
			examples: 'fish, owl, lion, raven, spider, unicorn',
		},
		{
			name: 'plant',
			examples: 'tree, apple, carrot, flower, mushroom, branch',
		},
		{
			name: 'natural',
			examples: 'lightning, diamond, sun, moon, fire, comet',
		},
		{
			name: 'body part',
			examples: 'eye, skull, hand, heart, teeth, claw',
		},
		{
			name: 'celestial body',
			examples: 'star, planet, comet, galaxy, constellation, nebula',
		},
		{
			name: 'mythical creature',
			examples: 'dragon, phoenix, griffin, centaur, sphinx, kraken',
		},
		{
			name: 'weather phenomenon',
			examples: 'storm, rainbow, tornado, fog, aurora, hailstorm',
		},
		{
			name: 'precious metal',
			examples: 'gold, silver, platinum, copper, bronze, titanium',
		},
	],
	gender: [
		{ icon: '<i class="fa-solid fa-mars"></i>', name: 'Male', pronoun: 'His' },
		{
			icon: '<i class="fa-solid fa-venus"></i>',
			name: 'Female',
			pronoun: 'Her',
		},
		{
			icon: '<i class="fa-solid fa-genderless"></i>',
			name: 'Genderless',
			pronoun: 'Their',
		},
	],
	name: [
		'mith',
		'tri',
		'dar',
		'gor',
		'an',
		'va',
		'col',
		'sige',
		'dir',
		'era',
		'altas',
		'remea',
		'fir',
		'alga',
		'lorra',
		'shiro',
		'velen',
		'amron',
		'for',
		'ened',
		'ziri',
		'red',
		'saur',
		'baal',
		'li',
		'serat',
		'cho',
		'maht',
		'alidren',
		'esh',
		'sae',
		'rah',
		'on',
		'tin',
		'ti',
		'ah',
		'kara',
		'zen',
		'yra',
		'quar',
		'olth',
		'thor',
		'elar',
		'ivra',
		'drek',
		'zo',
		'gryn',
		'jara',
		'yond',
		'xan',
		'ren',
		'dras',
		'syr',
		'karn',
		'ex',
		'lorn',
		'san',
		'ver',
		'gar',
		'cal',
		'morn',
		'thra',
		'esh',
		'zor',
		'fyr',
		'par',
		'quen',
		'tash',
		'syl',
		'vyr',
		'lyn',
		'xel',
		'zhal',
		'yss',
		'nar',
		'thir',
		'quar',
		'xir',
		'zhul',
		'kyl',
		'yol',
		'thor',
		'vel',
		'nyx',
		'qel',
		'fyr',
		'shyra',
		'vahl',
		'zer',
		'mys',
		'nyss',
		'qen',
		'xar',
		'lith',
	],
	sacredSite: [
		'bottomless pit',
		'lone mountain',
		'hot spring',
		'rock tower',
		'small lake',
		'ancient tree',
		'cave',
		'volcano',
		'grove',
		'henge',
		'geyser',
		'eternal flame',
		'whispering waterfall',
		'mystic ruins',
		'singing sands',
		'starfall crater',
	],
};

export default deityData;
